---
# Name the file secrets.yml

development:
  API_HOST: http://localhost:9090
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/dev.db
  DATABASE_URL: postgres://postgres:postgres_passwd@postgres-db:5432/dev
  REPOSTORE_PATH: app/infrastructure/git/repostore
  MONGO_URL: 'mongo-db:27017/dev'
  GITHUB_TOKEN: <personal access token for github api>
  REDISCLOUD_URL: <set by Heroku provisioned Redis>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>

test:
  API_HOST: http://localhost:9090
    # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/test.db
  DATABASE_URL: postgres://postgres:postgres_passwd@postgres-db:5432/test
  REPOSTORE_PATH: app/infrastructure/git/repostore
  MONGO_URL: 'mongo-db:27017/test'
  GITHUB_TOKEN: <personal access token for github api>
  REDISCLOUD_URL: <set by Heroku provisioned Redis>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>

production:
  GITHUB_TOKEN: <personal access token for github api>
  REDISCLOUD_URL: <set by Heroku provisioned Redis>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>